name: Install Terraform
description: "Terraform install and setup version via tfenv"
inputs:
  TerraformVersion:
    description: 'Terraform Version.'
    required: true
    default: ''
  TerragruntVersion:
    description: 'Terraform Version.'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Terraform Install
      run: |
        git \
        clone \
        --depth=1 \
        https://github.com/tfutils/tfenv.git \
        ~/.tfenv
      shell: bash

    - name: Terraform Setup Environment
      run: |
        echo  "$HOME/.tfenv/bin" >> $GITHUB_PATH
      shell: bash

    - name: Terraform Setup Version
      run: |
        tfenv install ${{ inputs.TerraformVersion }} && \
        tfenv use ${{ inputs.TerraformVersion }}
      shell: bash

    - name: Terragrunt Install
      run: |
        git \
        clone \
        https://github.com/cunymatthieu/tgenv.git \
        ~/.tgenv
      shell: bash

    - name: Terragrunt Setup Environment
      run: |
        echo  "$HOME/.tgenv/bin" >> $GITHUB_PATH
      shell: bash

    - name: Terragrunt Setup Version
      run: |
        tgenv install ${{ inputs.TerragruntVersion }} && \
        tgenv use ${{ inputs.TerragruntVersion }}
      shell: bash