name: Install Terraform
description: "Terraform install and setup version via tfenv"
inputs:
  version:
    description: 'Terraform Version.'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Terraform Install
      run: |
        git \
        clone \
        --depth=1 \
        https://github.com/tfutils/tfenv.git \
        ~/.tfenv
      shell: bash

    - name: Terraform Setup Environment
      run: |
        echo \
        export ".tfenv/bin" >> $GITHUB_PATH
      shell: bash

    - name: Terraform Setup Version
      run: |
        tfenv install ${{ inputs.version }} && \
        tfenv use ${{ inputs.version }}
      shell: bash