# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

parameters:
  - name: yesNo
    type: boolean
    default: false

steps:
  - script: echo ${{parameters.yesNo}}
  - script:  git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
  - script:  echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> ~/.bash_profile
  - script: ~/.tfenv --version
  - script: tfenv --version