trigger:
- master

resources:
  repositories:
    - repository: azure-devops-templates
      type: github
      name: Dev-Marques-Ops-Templates/azure-devops-templates
      #endpoint: github.com_marquesmateus93
      endpoint: : Marques

jobs:
- template: terraform-terragrunt.yaml@azure-devops-templates
  parameters:
    TerragruntWorkDir: dev/us-east-1/tags/