trigger:
- master

parameters:
  - name: TerraformAddress
    type: string
    default: https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip

  - name: TerraformVersion
    type: string
    default: 1.1.7

  - name: TerragruntAddress
    type: string
    default: "https://github.com/gruntwork-io/terragrunt/releases/download/v$TERRAGRUNT_VERSION/terragrunt_linux_amd64"

  - name: TerragruntVersion
    type: string
    default: 0.36.6

jobs:

- job: 'Terraform'
  steps:
    - script: |
        curl -SL ${{parameters.TerraformAddress}} -o ~/terraform.zip
        ls -lth ~/
        unzip ~/terraform.zip
        chmod +x ~/terraform
        ln -s terraform  ~/.local/bin/terraform
        terragrunt --version
      env:
        TERRAFORM_VERSION: ${{parameters.TerraformVersion}}
      displayName: 'Setup'

- job: 'Terragrunt'
  dependsOn: 'Terraform'
  steps:
    - script: |
        curl -SL ${{parameters.TerragruntAddress}} --output ~/terragrunt
        chmod +x ~/terragrunt
        ./terragrunt --version
      env:
        TERRAGRUNT_VERSION: ${{parameters.TerragruntVersion}}
      displayName: 'Setup'