resources:
  repositories:
    - repository: azure-devops-templates
      type: github
      name: Dev-Marques-Ops-Templates/azure-devops-templates
      endpoint: Marques

parameters:
  - name: TerragruntWorkDir
    type: string
    default: "dev/us-east-1/vpc"

variables:
  - group: AWS
  - group: GitHub

steps:
  - template: awscli/install.yaml@azure-devops-templates
  - template: terraform/install.yaml@azure-devops-templates
  - template: terragrunt/install.yaml@azure-devops-templates
  - template: git/setup.yaml@azure-devops-templates
    parameters:
      KnownHostsEntry: $(SSHKeySecureFile)
      SSHKeySecureFile: 'Azure Devops'
  - template: terragrunt/format.yaml@azure-devops-templates
    parameters:
      TerragruntWorkDir: ${{parameters.TerragruntWorkDir}}
  - template: terragrunt/plan.yaml@azure-devops-templates
    parameters:
      TerragruntWorkDir: ${{parameters.TerragruntWorkDir}}
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)