trigger:
- master

parameters:
  - name: yesNo
    type: boolean
    default: false

steps:
  - script: |
    echo ${{parameters.yesNo}}
    git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
    ~/.tfenv/bin/tfenv --version
    tfenv --version
