trigger:
- master

parameters:
  - name: TerraformAddress
    type: string
    default: https://github.com/tfutils/tfenv.git

  - name: TerraformVersion
    type: string
    default: 1.1.7

steps:
  - script: |
      git clone --depth=1 ${{parameters.TerraformAddress}} ~/.tfenv 
      ~/.tfenv/bin/tfenv --version
    displayName: 'Terraform Install'
  - script: |
      ~/.tfenv/bin/tfenv install ${{parameters.TerraformVersion}}
      ~/.tfenv/bin/tfenv use ${{parameters.TerraformVersion}}
    displayName: 'Terraform Version Setup'