trigger:
- master

parameters:
  - name: TerraformAddress
    type: string
    default: https://github.com/tfutils/tfenv.git

  - name: TerraformVersion
    type: string
    default: 1.1.7

  - name: TerragruntAddress
    type: string
    default: https://github.com/cunymatthieu/tgenv.git

  - name: TerragruntVersion
    type: string
    default: 0.36.6

jobs:

- job: 'TerraformInstall'
  displayName: 'Terraform Install'
  steps:
    - script: |
        git clone --depth=1 ${{parameters.TerraformAddress}} ~/.tfenv
        ln -s ~/.tfenv/bin/* ~/.local/bin
        ~/.tfenv/bin/tfenv --version
      displayName: 'Download'
    - script: |
        ~/.tfenv/bin/tfenv install ${{parameters.TerraformVersion}}
        ~/.tfenv/bin/tfenv use ${{parameters.TerraformVersion}}
      displayName: 'Version Setup'

- job: 'TerragruntInstall'
  displayName: 'Terragrunt Install'
  dependsOn: 'TerraformInstall'
  steps:
    - script: |
        git clone ${{parameters.TerragruntAddress}} ~/.tgenv
        echo 'export PATH="~/.tgenv/bin:$PATH"' >> ~/.bash_profile
        ~/.tgenv/bin/tgenv --version
      displayName: 'Download'
    - script: |
        ~/.tgenv/bin/tgenv install ${{parameters.TerragruntVersion}}
        ~/.tgenv/bin/tgenv use ${{parameters.TerragruntVersion}}
      displayName: 'Version Setup'