resources:
  repositories:
    - repository: azure-devops-templates
      type: github
      name: Dev-Marques-Ops-Templates/azure-devops-templates
      endpoint: Marques

parameters:
  - name: GIT_SSH_COMMAND
    type: string

variables:
  - group: AWS
  - group: GitHub

steps:
  - template: awscli/install.yaml@azure-devops-templates
  - template: terraform/install.yaml@azure-devops-templates
  - template: terragrunt/install.yaml@azure-devops-templates
  - bash: GIT_SSH_COMMAND='ssh -i $(GIT_SSH_COMMAND)'
  - template: terragrunt/plan.yaml@azure-devops-templates
    parameters:
      TerragruntWorkDir: dev/us-east-1/tags
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)