resources:
  repositories:
    - repository: templates
      type: github
      name: Dev-Marques-Ops-Templates/azure-devops-templates
      endpoint: Marques

parameters:
  - name: TerragruntWorkDir
    type: string
    default: "dev/us-east-1/vpc"

variables:
  - group: AWS
  - group: GitHub

steps:
  - template: templates/terragrunt-apply-workflow.yaml@templates
    parameters:
      TerragruntWorkDir: ${{parameters.TerragruntWorkDir}}
      KnownHostsEntry: $(SSHKeySecureFile)
      SSHKeySecureFile: 'Azure Devops'
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)