parameters:
  - name: TerraformAddress
    type: string
    default: https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip

  - name: TerragruntAddress
    type: string
    default: https://github.com/gruntwork-io/terragrunt/releases/download/v"$TERRAGRUNT_VERSION"/terragrunt_linux_amd64

  - name: TerragruntWorkDir
    type: string
    default: .

  - name: TerraformVersion
    type: string
    default: 1.1.7

  - name: TerragruntVersion
    type: string
    default: 0.36.6


steps:
  - bash: |
      DIRECTORY=$(Build.SourcesDirectory)/terraform/${{parameters.TerraformVersion}}
      
      mkdir -p $DIRECTORY
      curl -SL ${{parameters.TerraformAddress}} -o ~/terraform.zip
      unzip ~/terraform.zip -d $DIRECTORY
      
      echo "##vso[task.prependpath]$DIRECTORY"
      sudo chmod +x $DIRECTORY/terraform
      terraform --version
      ls -lth ~/
      ls -lth $DIRECTORY
    env:
      TERRAFORM_VERSION: ${{parameters.TerraformVersion}}
    displayName: 'Terraform Install'

  - bash: |
      DIRECTORY=$(Build.SourcesDirectory)/terragrunt/${{parameters.TerragruntVersion}}
      
      mkdir -p $DIRECTORY
      curl -SL ${{parameters.TerragruntAddress}} > $DIRECTORY/terragrunt
      sudo chmod +x $DIRECTORY/terragrunt
      
      echo "##vso[task.prependpath]$DIRECTORY"
      terragrunt --version
      ls -lth ~/
      ls -lth $DIRECTORY
    env:
      TERRAGRUNT_VERSION: ${{parameters.TerragruntVersion}}
    displayName: 'Terragrunt Install'
  - script: |
      #terragrunt plan --terragrunt-working-dir ${{parameters.TerragruntWorkDir}}
      terraform --version
      terragrunt --version
    displayName: 'Terragrunt Plan'