resources:
  repositories:
    - repository: azure-devops-templates
      type: github
      name: Dev-Marques-Ops-Templates/azure-devops-templates
      endpoint: Marques

variables:
  - group: AWS
  - group: GitHub

  - name: TerragruntWorkDir
    value: 'dev/us-east-1'
  - name: TerragruntPaths
    value: ["tags", "vpc"]

steps:
  - template: awscli/install.yaml@azure-devops-templates
  - template: terraform/install.yaml@azure-devops-templates
  - template: terragrunt/install.yaml@azure-devops-templates
  - template: git/setup.yaml@azure-devops-templates
    parameters:
      KnownHostsEntry: $(SSHKeySecureFile)
      SSHKeySecureFile: 'Azure Devops'
  - template: terragrunt/format.yaml@azure-devops-templates
    parameters:
      TerragruntWorkDir: $(TerragruntWorkDir)
      TerragruntPaths: $(TerragruntPaths)
  - template: terragrunt/plan.yaml@azure-devops-templates
    parameters:
      TerragruntWorkDir: $(TerragruntWorkDir)
      TerragruntPaths: $(TerragruntPaths)