trigger:
- master

parameters:
  - name: TerraformAddress
    type: string
    default: https://github.com/tfutils/tfenv.git

  - name: TerraformVersion
    type: string
    default: 1.1.7

  - name: TerragruntAddress
    type: string
    default: https://github.com/cunymatthieu/tgenv.git

  - name: TerragruntVersion
    type: string
    default: 0.36.6

jobs:

- job: 'TerraformInstall'
  displayName: 'Terraform Install'
  steps:
    - script: |
        git clone --depth=1 ${{parameters.TerraformAddress}} ~/.tfenv
        ln -s ~/.tfenv/bin/* ~/.local/bin
        ~/.tfenv/bin/tfenv --version
      displayName: 'Download'
    - script: |
        ~/.tfenv/bin/tfenv install ${{parameters.TerraformVersion}}
        ~/.tfenv/bin/tfenv use ${{parameters.TerraformVersion}}
      displayName: 'Version Setup'

- job: 'TerragruntInstall'
  displayName: 'Terragrunt Install'
  dependsOn: 'TerraformInstall'
  steps:
    - script: |
        curl -SL https://github.com/gruntwork-io/terragrunt/releases/download/v"${{parameters.TerragruntVersion}}"/terragrunt_linux_amd64 -O terragrunt
        terragrunt --version
      env:
        TGENV_ROOT: ~/.tgenv
      displayName: 'Download'