trigger:
- master

resources:
  repositories:
    - repository: azure-devops-templates
      type: github
      name: Dev-Marques-Ops-Templates/azure-devops-templates
      ref: refs/heads/main
      #endpoint: Dev-Marques-Ops-Live-Infrastructure

jobs:
- template: terraform-terragrunt.yaml@azure-devops-templates