name: VPC Deploy
on:
  push:
    paths:
      - 'dev/**'
      - 'sta/**'
      - 'pro/**'
  workflow_dispatch:

env:
  AWS_REGION:         ${{ vars.AWS_DEFAULT_REGION }}
  TERRAFORM_VERSION:  ${{ vars.TERRAFORM_VERSION }}
  TERRAGRUNT_VERSION: ${{ vars.TERRAGRUNT_VERSION }}

jobs:
  VPC_Deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Paths Filter
        id: paths_filter
        uses: marquesmateus93/actions-templates/paths-filter@master
        env:
          AWS_DEV_ACCOUNT:  ${{ vars.AWS_DEV_ACCOUNT }}
          AWS_STA_ACCOUNT:  ${{ vars.AWS_STA_ACCOUNT }}
          AWS_PRO_ACCOUNT:  ${{ vars.AWS_PRO_ACCOUNT }}

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ steps.paths_filter.outputs.AWS_ACCOUNT }}:role/GitHubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Install
        uses: marquesmateus93/actions-templates/terraform@master
        env:
          TERRAFORM_VERSION: ${{ env.TERRAFORM_VERSION }}

      - name: Terragrunt Install
        uses: marquesmateus93/actions-templates/terragrunt@master
        env:
          TERRAGRUNT_VERSION: ${{ env.TERRAGRUNT_VERSION }}
          TERRAGRUNT_PATH:    ${{ steps.paths_filter.outputs.ENV_FOLDER }}/${{ env.AWS_REGION }}