name: Terragrunt VPC Apply
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  ACCOUNT_NUMBER:     ${{ github.ref == 'refs/heads/master' && vars.AWS_DEV_ACCOUNT }}
  AWS_REGION:         ${{ vars.AWS_DEFAULT_REGION }}
  terraformVersion:   ${{ vars.TERRAFORM_VERSION }}
  terragruntVersion:  ${{ vars.TERRAGRUNT_VERSION }}
  terragruntPath:     ${{ vars.DEV_ENV }}/${{ vars.AWS_DEFAULT_REGION }}

jobs:
  TerragruntVPCDeploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/GitHubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Install
        uses: marquesmateus93/actions-templates/terraform@master
        env:
          terraformVersion: ${{ env.terraformVersion }}

      - name: Terragrunt Install
        uses: marquesmateus93/actions-templates/terragrunt@master
        env:
          terragruntVersion: ${{ env.terragruntVersion }}
          terragruntPath:   ${{ env.terragruntPath }}