name: Terragrunt VPC Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  TerragruntVPCDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and setup version.
        uses: ./
        with:
          TerraformVersion: 1.3.6
          TerragruntVersion: 0.42.5